### ISSUE TITLE
Defaults to config too quickly after wifi connection loss

### ISSUE THREAD

**Issue by hemiawd** [liebman/ESPNTPServer#4]
Hi Liebman,

Great project, works great. I have encountered an issue in my environment that could possibly enhance the project for others. I am looking to use this as a highly available NTP server for my environment.

My wifi reboots weekly in the middle of the night. When this happens, the ESP detects the loss and before the wifi is reconnected the ESP goes to broadcasting it's own SSID for config mode. This takes the NTP server offline until I manually restart it. Is there a way to incorporate a configurable delay in seconds for the wifi reconnect when there is an existing config in place. Or another idea is a configurable parameter that just keeps attempting reconnects and blocks config mode from being entered unless the button is pressed. 

Thanks for considering these suggestions.

**Comment by liebman** [comment]
This should be doable.  I'm using WiFiManager and I know it has options to set the connect timeout.

**Comment by liebman** [comment]
OK - I've created a branch `disable-auto-captive-portal` can you give that a try?  This is what "should" happen:
- the captive portal will start if the config button is held at power up/reset
- on a fresh (erased) unit the config file will not exist in SPIFFS and captive portal will start
- if it has a config file it will connect but NOT start the portal. (if its failing to connect it will delay one second and try again forever)

Let me know if this works for your use case and if so I'll merge to master.

**Comment by hemiawd** [comment]
Yes, it waited out for the wifi to return and then successfully reconnected, awesome thanks. Actually rebooted 3 times and it recovered each so appears to be in great shape. All other functions appear at they were prior. When wifi comes back it does delay the 120 seconds before becoming valid again.
