### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by cyber-junkie9** [liebman/ESPNTPServer#6]
Hello 
thank you for such an awesome project but i have a query regarding RTC module (DS3231) 
is it possible to add RTC module? i need a simple local NTP server for my projects to keep time up to date
it works very well with GPS but sometime i don't get proper signal with GPS due to bad weather and after electricity cut-off my all devices looses time :/

**Comment by liebman** [comment]
While it is possible I generally include an DS3231 on any project that is that sensitive to time and use the NTP server to set it periodically. For instance I did that [here](https://github.com/liebman/AnalogClock).

**Comment by cyber-junkie9** [comment]
Thank you for quick response but i need local NTP server(wthout gps) not for just single device

**Comment by liebman** [comment]
@tech-freak an update is that I've been toying with using an ESP32+DS3231 and using the AGEOFFSET register on the DS3231 to make small adjustments to compensate for the natural drift (can be a few PPM) and to make small (less that 500us) adjustments to sync the DS3231 to the GPS.

**Comment by cyber-junkie9** [comment]
thank you for your time but i switched to ESP32+DS3231 based different project and its working fine
